// <auto-generated />
using System;
using DermaScanAgent.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DermaScanAgent.Migrations
{
    [DbContext(typeof(SkinCancerAgentDbContext))]
    partial class SkinCancerAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiAgents.SkinCancerAgent.Domain.Entities.LesionImageSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LesionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageSamples");
                });

            modelBuilder.Entity("DermaScanAgent.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("PredictedLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("DermaScanAgent.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AutoThresholdHigh")
                        .HasColumnType("real");

                    b.Property<float>("AutoThresholdLow")
                        .HasColumnType("real");

                    b.Property<bool>("IsRetrainEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("NewGoldSinceLastTrain")
                        .HasColumnType("int");

                    b.Property<int>("RetrainGoldThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoThresholdHigh = 0.85f,
                            AutoThresholdLow = 0.2f,
                            IsRetrainEnabled = true,
                            NewGoldSinceLastTrain = 0,
                            RetrainGoldThreshold = 20
                        });
                });

            modelBuilder.Entity("DermaScanAgent.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("AiAgents.SkinCancerAgent.Domain.Entities.LesionImageSample", null)
                        .WithMany("Predictions")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiAgents.SkinCancerAgent.Domain.Entities.LesionImageSample", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
